services:
  rabbit-1:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbit-1
    hostname: rabbit-1 
    networks:
      - net
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcluster
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=xoxo
    volumes:
      - rabbitmq-1-data:/var/lib/rabbitmq
  rabbit-2:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbit-2
    hostname: rabbit-2
    networks:
      - net
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcluster
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=xoxo
    volumes:
      - rabbitmq-2-data:/var/lib/rabbitmq
  rabbit-3:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbit-3
    hostname: rabbit-3
    networks:
      - net
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcluster
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=xoxo
    volumes:
      - rabbitmq-3-data:/var/lib/rabbitmq

volumes:
  rabbitmq-1-data:
    driver: local
  rabbitmq-2-data:
    driver: local
  rabbitmq-3-data:
    driver: local

networks:
  net:
    driver: bridge
